name: Deploy to Firebase Hosting on PR
on: pull_request

jobs:
  ProdBuild:
    if: |
      ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd client && npm install && npm run build:dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: client
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAME_HARBOR_DEVELOP }}'
          expires: 3d
          projectId: game-harbor-develop
