name: Deploy to Firebase Hosting on PR
on: pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log files before cd current files
        run: ls -la

      - name: Go to client directory
        run: cd client

      - name: Log files after cd current files
        run: ls -la

      - run: yarn && yarn build:dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAME_HARBOR_DEVELOP }}'
          expires: 3d
          projectId: calendar-landing-develop